version: '3.8'

services:
  # MongoDB service
  mongodb:
    image: mongo:6.0
    container_name: mern-mongodb
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=mernapp
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: my-node-backend
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=5000
      - MONGO_URI=mongodb://admin:secret@mongodb:27017/mernapp?authSource=admin
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongodb

  # Frontend service
  frontend:
    build:
      context: ./book_store
      dockerfile: Dockerfile
    container_name: my-react-app
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mongodb_data:
    driver: local