name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger

jobs:
  build-deploy:
    runs-on: self-hosted #self hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        minikube start
        eval $(minikube docker-env)

    - name: Build Frontend Docker image
      run: |
        docker build -t ahmadbehzad/scd-frontend:latest ./book_store

    - name: Build Backend Docker image
      run: |
        docker build -t ahmadbehzad/scd-backend:latest ./backend

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Frontend Docker image to Docker Hub
      run: docker push ahmadbehzad/scd-backend:latest

    - name: Push Backend Docker image to Docker Hub
      run: docker push ahmadbehzad/scd-backend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f mongodb-config.yml
        kubectl apply -f mongodb-deployment-statefulset.yml
        kubectl apply -f mongodb_pvc.yml
        kubectl apply -f mongodb_secret.yml
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml