name: Build and Deploy to Minikube

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger

jobs:
  build-deploy:
    runs-on: self-hosted #self hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker to use Minikube's environment
      run: |
        echo "Configuring Docker to use Minikube's daemon..."
        minikube start
        & minikube -p master docker-env --shell powershell | Invoke-Expression

    - name: Build Frontend Docker image
      run: |
        docker build -t ahmadbehzad/scd-frontend:latest ./book_store

    - name: Build Backend Docker image
      run: |
        docker build -t ahmadbehzad/scd-backend:latest ./backend

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Push Frontend Docker image to Docker Hub
      run: docker push ahmadbehzad/scd-backend:latest

    - name: Push Backend Docker image to Docker Hub
      run: docker push ahmadbehzad/scd-backend:latest

    - name: Deploy to Minikube
      run: |
        kubectl apply -f mongodb-config.yml
        kubectl apply -f mongodb-deployment-statefulset.yml
        kubectl apply -f mongodb_pvc.yml
        kubectl apply -f mongodb_secret.yml
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml